{% set name = "show-in-file-manager" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 15d16e4a875b9e217b038d02f029c3800c4a6ad645e3f73c9e107ea26bab3adb

build:
  skip: True  # [py<38]
  entry_points:
    - "showinfilemanager = showinfm.showinfm:main"
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python
    - pip
  run:
    - python
    - packaging
    - pyxdg  # [linux]
    - pywin32  # [win]
test:
  imports:
    - showinfm
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/damonlynch/showinfilemanager
  license: MIT
  license_file: LICENSE
  summary: "A Python package to open the system file manager and optionally select files in it."

extra:
  recipe-maintainers:
    - JoeZiminski
