{% set name = "show-in-file-manager" %}
{% set version = "1.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ed13a180a1d48fd88fdd4c58bfbcb3860268641a38805192c814d41387192d84

build:
  skip: true  # [py<38]
  entry_points:
    - "showinfilemanager = showinfm.showinfm:main"
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - tomli
    - argparse-manpage
  run:
    - python
    - packaging
    - pyxdg  # [linux]
    - pywin32  # [win]
test:
  imports:
    - showinfm
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/damonlynch/showinfilemanager
  license: MIT
  license_file: LICENSE
  summary: "A Python package to open the system file manager and optionally select files in it."

extra:
  recipe-maintainers:
    - JoeZiminski
